/*
  #+TITLE: Dank Material Shell
  #+FILETAGS: :ui:

  * Key configuration
     https://github.com/AvengeMedia/DankMaterialShell/blob/293c2a0035119a87f831be856161138a5d36f437/distro/nix/niri.nix#L110
     - M+Space -> applications
     - M+N -> notifications
     - M+Comma -> settings
     - M+P -> notepad
     - M+Alt+L -> lock screen
     - M+X -> power menu
     - M+Alt+N -> night mode
     - M+V -> clipboard
     - M+M -> processes
*/
{ sources, ... }:

let
  shell = (import sources.flake-compat { src = sources.DankMaterialShell; }).outputs;
  dgop = (import sources.flake-compat { src = sources.dgop; }).outputs;
  dsearch = (import sources.flake-compat { src = sources.danksearch; }).outputs;
in
{
  imports = [
    shell.homeModules.dank-material-shell
    shell.homeModules.niri
    dsearch.homeModules.default
  ];

  programs.dsearch.enable = true;
  programs.dank-material-shell = {
    enable = true;
    dgop.package = dgop.packages.${builtins.currentSystem}.dgop;

    niri.enableSpawn = true;
    # [26.03.2026] TODO This is a upstream hack to seed niri with DMS settings! Keep an eye on it
    niri.includes = {
      enable = true; # Enable config includes hack. Enabled by default.

      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab"
        # "binds" -> own binds
        "cursor"
        "colors"
        "layout"
        "outputs"
        "wpblur"
        "windowrules"
      ];
    };

    # Core features
    enableSystemMonitoring = true; # System monitoring widgets (dgop)
    enableVPN = false; # VPN management widget
    enableDynamicTheming = true; # Wallpaper-based theming (matugen)
    enableAudioWavelength = false; # Audio visualizer (cava)
    enableCalendarEvents = false; # Calendar integration (khal)
    enableClipboardPaste = true; # Pasting items from the clipboard (wtype)
  };
}
