#+STARTUP: content

* Sysconf - an opinionated home of Nix* systems
#+begin_quote
Once upon a time, in the pale light of the winters sun, the narrator sat in front of his even paler screen. He was hacking in anger, exhausted about the hours -  heck even days, he would have to commit setting up an death simple computing environment. While stuck in the loop of following yet another manual he expressed a silent "Never again": this time artifacts should be more streamlined, more clear, more deterministic, more flexible, more documented, more more

So he looked back up again and went on his long journey down the nix* rabbit hole...
#+end_quote

This repository is the continuos pathway reaching the goal:
- A fully reproducible system sitting on shoulders of [[https://nixos.org/][NixOS]] and the allmighty [[https://github.com/nix-community/home-manager][Home Manager]].
- A bare metal system or full desktop envirnoment.
- A bag full of opinionated choices but documented enough to adapt it to your opinionated needs.

* Contents :toc:
- [[#sysconf---an-opinionated-home-of-nix-systems][Sysconf - an opinionated home of Nix* systems]]
- [[#a-short-list-of-ingredients][A short list of ingredients]]
  - [[#docs][./docs]]
  - [[#_home-manager][./_home-manager]]
  - [[#_secret][./_secret]]
  - [[#nixos][./nixOS]]
  - [[#nix][./nix]]
- [[#where-to-start][Where to start?]]
  - [[#i-want-to-run-nixos-in-a-virtualbox-et-cetera][I want to run NixOS in a VirtualBox (et cetera)]]
  - [[#i-have-a-running-linux-machine-and-want-to-manage-my-packages-with-nix][I have a running Linux machine and want to manage my packages with Nix]]
  - [[#i-already-have-a-machine-running-windows-and-want-dual-boot-nixos-alongside][I already have a machine running Windows and want dual boot NixOS alongside]]
  - [[#i-have-just-want-a-nixos-machine][I have just want a NixOS machine]]
- [[#used-filetags][Used FILETAGS]]

* A short list of ingredients
** [[file:docs/][./docs]]
While many moving parts are pretty declarative in here, some parts simply can't. In this folder you'll find mostly /pre intallation/ writings like setting up a filesystem or arch installation walkthrough. Probably also some ramblings about nix systems and tooling which are a bit side tracked from the actual installation.
** [[file:_home-manager/][./_home-manager]]
From scratch I tried to push as [[https://rycee.gitlab.io/home-manager/options.html][many configurations as possible]] to the mentioned Home Manager. Home Manager is, as the name suggests, a /user environment manager/ made for nix* systems. This is the most valueable part of the configuration as most of the *systems software* is made up by those configurations.

Home Manager sits in between [[file:nixOS/][nixOS]] and [[file:nix/][nix]] as configurations can be applied on both. How to install Home Manager? See [[file:docs/][./docs]] for home manager installation or the respective [[https://github.com/nix-community/home-manager][Home Manager GitHub]] repository.
** [[file:_secret/][./_secret]]
Sensitive artifacts needed for my system to work; encrypted with [[https://git-secret.io/][Git Secret]].
** [[file:nixOS/][./nixOS]]
This folder contains the nixOS installations I have running each with it's on documentation.
** [[file:nix/][./nix]]
This folder contains bundled home manager packages to be consumed by any system running the nix* package manager.

* Where to start?
This depends highly on your use case. It first may be a good idea to look around make yourself comfortable
** I want to run NixOS in a VirtualBox (et cetera)

** I have a running Linux machine and want to manage my packages with Nix
** I already have a machine running Windows and want dual boot NixOS alongside
** I have just want a NixOS machine

* Used FILETAGS
alarcitty -> :shell:ui:sway:
blueman -> :ui:sway:
direnv -> :development:
emails -> :user:
exa -> :navigation:
fish -> :shell:development:
gammastep -> :ui:sway:
git -> :development:
gpg -> :encrypt:auth:ssh:
gtk -> :ui:
lorri -> :development:
mako -> :ui:sway:
ssh -> :shell:
systemd -> :user:
udiskie -> :hardware:
xdg -> :ui:

brave -> :program:
emacs -> :program:
sizzy -> :development:
sway -> :sway:
waybar -> :sway:
zathura -> :program:

overlays -> :user:sway:
