#!/bin/sh

filestart="$HOME/Pictures/screenshot_"
ts=$(date +'%Y-%m-%d-%H:%M:%S')

fname="$filestart$ts.png"

if [ "$1" = "full" ]; then
    grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name') $fname
else
    grim -g "$(slurp)" $fname
fi
