#!/usr/bin/env bash
# Switch PipeWire port of the default audio sink.
# This is a scripted approach following the official docs:
# https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Migrate-PulseAudio#sinksource-port-volumemuteport-latency
#
# CAUTION: It's a hack but it works for me.
#
# Usage:
#  $ ./switch-audio-port

# Obligatory Auto-Mute Disable
amixer -c 0 sset 'Auto-Mute Mode' Disabled --quiet

DI=$(pw-cli ls Device | grep -zoP "id \d\d(?:(?!id \d\d)(.|\n))*?Audio\/Device" | sed -n 's/id\s\(\S*\),.*$/\1/p')

PRO=$(pw-cli e $DI Profile | grep -zoP "Profile:index(.|\n)*?Int \d" | tr -d '\0' | tail -c2)

# Super quick and dirty
if [ "$PRO" -eq "1" ]; then
	pw-cli s $DI Profile '{ index: 2, save: true }' 1>/dev/null
else
	pw-cli s $DI Profile '{ index: 1, save: true }' 1>/dev/null
fi
